tap 'caskroom/cask'
tap 'caskroom/versions'

# Required for maven and gradle, therefore install it first
cask 'java'

brew 'coreutils'
brew 'docker'
brew 'exa'
brew 'fzf'
brew 'ghostscript'
brew 'git'
brew 'git-archive-all'
brew 'git-lfs'
brew 'gradle'
brew 'groovy'
brew 'htop'
brew 'httpie'
brew 'icdiff'
brew 'jq'
brew 'maven'
brew 'ncdu'
brew 'ncurses'
brew 'neovim'
brew 'node'
brew 'rclone'
brew 'reattach-to-user-namespace'
brew 'ripgrep'
brew 'tig'
brew 'tmux'

cask 'adium'
cask 'adobe-acrobat-reader'
cask 'appcleaner'
cask 'cyberduck'
cask 'dash'
cask 'docker'
cask 'exifrenamer'
cask 'firefoxnightly'
cask 'firefoxdeveloperedition'
cask 'hammerspoon'
cask 'hex-fiend'
cask 'iina'
cask 'imageoptim'
cask 'intellij-idea'
cask 'iterm2-beta'
cask 'jce-unlimited-strength-policy'
cask 'safari-technology-preview'
cask 'sequel-pro'
cask 'tower'
cask 'tunnelblick-beta'
cask 'vimr'
cask 'vmware-fusion'

mas '1Password', id: 443987910
mas 'Cookie 5', id: 1048338802
mas 'Keynote', id: 409183694
mas 'Microsoft Remote Desktop', id: 715768417
mas 'Numbers', id: 409203825
mas 'Pages', id: 409201541
mas 'Pixelmator', id: 407963104
mas 'Reeder', id: 880001334
mas 'Xcode', id: 497799835
mas 'The Unarchiver', id: 425424353
