gui:
  windowSize: half
  showCommandLog: false
  expandFocusedSidePanel: true
  theme:
    selectedLineBgColor:
      - reverse
    selectedRangeBgColor:
      - reverse
git:
  paging:
    colorArg: always
    pager: delta --syntax-theme=TwoDark --paging=never
keybinding:
  universal:
    prevItem-alt: 'j'
    nextItem-alt: 'k'
    scrollUpMain-alt1: 'J'
    scrollDownMain-alt1: 'K'
    scrollUpMain-alt2: '<c-j>'
    scrollDownMain-alt2: '<c-k>'
  commits:
    moveUpCommit: '<c-j>'
    moveDownCommit: '<c-k>'
