gui:
  scrollHeight: 4
  skipUnstageLineWarning: true
  expandFocusedSidePanel: true
  showIcons: true
  theme:
    selectedLineBgColor:
      - reverse
    selectedRangeBgColor:
      - reverse
    activeBorderColor:
      - white
      - bold
    inactiveBorderColor:
      - '#7F848E'
    cherryPickedCommitBgColor:
      - blue
    cherryPickedCommitFgColor:
      - black
os:
  editCommand: 'hx'
  editCommandTemplate: '{{editor}} {{filename}}:{{line}}'
  openCommand: 'open {{filename}}'
git:
  paging:
    colorArg: always
    pager: delta --syntax-theme=TwoDark --paging=never
  log:
    showGraph: 'always'
keybinding:
  universal:
    prevItem-alt: 'j'
    nextItem-alt: 'k'
    scrollUpMain-alt1: 'J'
    scrollDownMain-alt1: 'K'
    scrollUpMain-alt2: '<c-j>'
    scrollDownMain-alt2: '<c-k>'
  commits:
    moveUpCommit: '<c-j>'
    moveDownCommit: '<c-k>'
notARepository: 'skip'
