gui:
  scrollHeight: 4
  skipUnstageLineWarning: true
  expandFocusedSidePanel: true
  showIcons: true
  theme:
    lightTheme: false 
    activeBorderColor:
      - white
      - bold
    inactiveBorderColor:
      - "#6e738d"
    selectedLineBgColor:
      - "#363a4f"
    selectedRangeBgColor:
      - "#5b6078"
    cherryPickedCommitBgColor:
      - "#363a4f"
    cherryPickedCommitFgColor:
      - "#cad3f5"
  editCommand: 'hx'
  editCommandTemplate: '{{editor}} {{filename}}:{{line}}'
  openCommand: 'open {{filename}}'
git:
  paging:
    colorArg: always
    pager: delta --paging=never
  log:
    showGraph: 'always'
keybinding:
  universal:
    prevItem-alt: 'j'
    nextItem-alt: 'k'
    scrollUpMain-alt1: 'J'
    scrollDownMain-alt1: 'K'
    scrollUpMain-alt2: '<c-j>'
    scrollDownMain-alt2: '<c-k>'
  commits:
    moveUpCommit: '<c-j>'
    moveDownCommit: '<c-k>'
notARepository: 'skip'
