user:
  - 238
  - 212
  - 159
group:
  - 245
  - 169
  - 127
permission:
  read:
    - 166
    - 218
    - 149
  write:
    - 238
    - 212
    - 159
  exec:
    - 237
    - 135
    - 150
  exec-sticky:
    - 198
    - 160
    - 246
  no-access:
    - 237
    - 135
    - 150
  octal:
    - 138
    - 173
    - 244
  acl:
    - 138
    - 173
    - 244
  context:
    - 183
    - 189
    - 248
date:
  hour-old:
    - 166
    - 218
    - 149
  day-old:
    - 139
    - 213
    - 202
  older:
    - 125
    - 196
    - 228
size:
  none:
    - 245
    - 189
    - 230
  small:
    - 240
    - 198
    - 198
  medium:
    - 238
    - 153
    - 160
  large:
    - 237
    - 135
    - 150
inode:
  valid:
    - 198
    - 160
    - 246
  invalid:
    - 237
    - 135
    - 150
links:
  valid:
    - 198
    - 160
    - 246
  invalid:
    - 237
    - 135
    - 150
tree-edge:
  - 110
  - 115
  - 162
