user:
  - 229
  - 200
  - 144
group:
  - 239
  - 159
  - 118
permission:
  read:
    - 166
    - 209
    - 137
  write:
    - 229
    - 200
    - 144
  exec:
    - 231
    - 130
    - 132
  exec-sticky:
    - 202
    - 158
    - 230
  no-access:
    - 231
    - 130
    - 132
  octal: 6
  acl:
    - 140
    - 170
    - 238
  context:
    - 186
    - 187
    - 241
date:
  hour-old:
    - 166
    - 209
    - 137
  day-old:
    - 129
    - 200
    - 190
  older:
    - 133
    - 193
    - 220
size:
  none:
    - 244
    - 184
    - 228
  small:
    - 238
    - 190
    - 190
  medium:
    - 234
    - 153
    - 156
  large:
    - 231
    - 130
    - 132
inode:
  valid: 13
  invalid: 245
links:
  valid:
    - 202
    - 158
    - 230
  invalid:
    - 231
    - 130
    - 132
tree-edge:
  - 115
  - 121
  - 148
